example:
  property: I AM THE DEFAULT

spring:
  jpa:
    show-sql : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      database: POSTGRESQL
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.postgresql.Driver
      
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'