example:
  property: I AM THE DEFAULT

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql : true
    hibernate:
      ddl-auto: none
      implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:  
      test-while-idle: true
      validation-query: SELECT 1
      
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    
resilience4j:
  circuitbreaker:
    instances:
      license-db:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 4
        ring-buffer-size-in-half-open-state: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
      organization-service:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 4
        ring-buffer-size-in-half-open-state: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
  bulkhead:
    instances:
      license-db:
        max-concurrent-calls: 2
        max-wait-duration: 10ms
  thread-pool-bulkhead:
    instances:
      license-db:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
        keep-alive-duration: 20ms
  retry:
    instances:
      license-db:
        max-attempts: 2
        wait-duration: 10000
  ratelimiter:
    instances:
      license-db:
        limit-for-period: 2
        limit-refresh-period: 5000
        timeout-duration: 1000ms
        
keycloak:
  realm: spmia-realm
  auth-server-url: http://host.docker.internal:8069/auth
  ssl-required: external
  resource: o-stock
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: 940d0a7c-8d42-43e3-b1f1-643eb8e23062