example:
  property: I AM THE DEFAULT

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql : true
    hibernate:
      ddl-auto: none
      implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:  
      test-while-idle: true
      validation-query: SELECT 1
      
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5