version: '3.8'

services:
  organization-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres4dev"
      POSTGRES_DB: "ostock_dev"
    volumes:
        - ./organization-db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./organization-db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "organization-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  licensing-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres4dev"
      POSTGRES_DB: "ostock_dev"
    volumes:
        - ./licensing-db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./licensing-db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "licensing-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config-server:
    image: ostock/config-server:0.0.1-SNAPSHOT
    environment:
      ENCRYPT_KEY: symmetric-key
      SPRING_PROFILES_ACTIVE: native
    ports:
       - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
  eureka-server:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071
    ports:
       - "8070:8070"
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-server"
  api-gateway-server:
    image: ostock/api-gateway-server:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071
    depends_on:
      config-server:
        condition: service_started
    ports:
      - "8072:8072"
    networks:
      backend:
        aliases:
          - "api-gateway-server"
  organization-service:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071
    depends_on:
      organization-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "organization-service"
  organization-service-2:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071
    depends_on:
      organization-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8083:8080"
    networks:
      backend:
        aliases:
          - "organization-service-2"
  licensing-service:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8071
    depends_on:
      licensing-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "licensing-service"
  
networks:
  backend:
    driver: bridge